services:
  apex-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: apex-db
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
    volumes:
      - ./config/startup:/opt/oracle/scripts/startup
      - ./config/setup:/opt/oracle/scripts/setup
    ports:
      - 1521:1521
      - 5500:5500
    healthcheck:
      test: [ "CMD", "/opt/oracle/checkDBStatus.sh"]
      interval: 2s
    networks:
      apex-net:
        aliases:
          - apex-db

  apex-ords:
    image: container-registry.oracle.com/database/ords-developer:latest
    container_name: apex-ords
    volumes:
      - ./config/variables:/opt/oracle/variables
    ports:
      - 80:8181
    depends_on:
      apex-db:
        condition: service_healthy
    networks:
      apex-net:
        aliases:
          - apex-ords

networks:
  apex-net:
    driver: bridge
